version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: hris-api
        container_name: hris-api-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - hris-api

    db:
        image: mysql:5.7
        container_name: hris-api-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysqldoc
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        ports:
            - "${DB_PORT}:3306"
        networks:
            - hris-api

    nginx:
        image: nginx:alpine
        container_name: hris-api-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - hris-api
    redis:
        image: redis:alpine
        container_name: hris-api-redis
        sysctls:
            - net.core.somaxconn=511
        ports:
            - "6379:6379"
        volumes:
            - ./docker-compose/redisdata:/data
        networks:
            - hris-api


networks:
    hris-api:
        driver: bridge
